# 数据库连接配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java_gobang?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapperLocations: classpath:mybatis/*Mapper.xml
#mybatis:
#  mapper-locations: classpath:mybatis/*Mapper.xml
# Mybatis配置
#mybatis:
#  #  mybatis保存路径
#  mapper-locations: classpath:com/example/gobang/mapper/*Mapper.xml
#  #  配置打印mybatis执行的sql
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
##  配置打印mybatis执行的sql
#logging:
#  level:
#    com:
#      example:
#        springmvcdemo: debug